version: "3.8"
services:
  web:
    container_name: appnode
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: clave
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 90:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: clave
      ME_CONFIG_MONGODB_URL: mongodb://root:clave@mongo:27017/